### ISSUE TITLE
Метабокс МойСклад у Продуктов пустой

### ISSUE THREAD

**Issue by aiiddqd** [yumashev/wooms#81]
Бывает что Продукт есть, но нет wooms_id. В этом случае метабокс МойСклад пустой.
Надо чтобы там было сообщение: Нет ссылки на МойСклад.

См снимок:
![image](https://user-images.githubusercontent.com/1852897/47388320-837e1580-d71a-11e8-80a5-b535b5bd2e15.png)

**Comment by artikus11** [comment]
@uptimizt  Понял, исправлю
